(deftheme vscode-dark
  "Created 2021-05-09.")

(custom-theme-set-faces
 'vscode-dark
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#c586c0"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#6a9955"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#4ec9b0"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#4ec9b0"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#ce9178"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#dcdcaa" :bold nil))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:bold nil :foreground "#569cd6"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#ce9178"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#4ec9b0"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#9cdcfe"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#f16969" :background "#252526"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#d7ba7d"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#d7ba7d"))))
 '(region ((((class color) (min-colors 89)) (:background "#264f78" :distant-foreground "#aeafad" :extend nil))))
 '(secondary-selection ((((class color) (min-colors 89)) (:inherit region))))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#4db2ff" :underline t))))
 '(fringe ((((class color) (min-colors 89)) (:background nil :foreground "#fafafa"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#d4d4d4"))))
 '(show-paren-match ((t (:foreground "#f4f4f4" :background "#4b474c" :bold t))))
 '(show-paren-mismatch ((t (:background "#f16969"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#613214"))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "black"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#4ec9b0" :weight normal))))
 '(link ((((class color) (min-colors 89)) (:foreground "#3794ff"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#ce9178"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#c586c0"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#4ec9b0"))))
 '(dired-directory ((t (:inherit (font-lock-keyword-face)))))
 '(line-number ((((class color) (min-colors 89)) (:inherit default :foreground "#838383"))))
 '(line-number-current-line ((((class color) (min-colors 89)) (:inherit line-number))))
 '(header-line ((((class color) (min-colors 89)) (:inherit nil :foreground "#ffffff" :background "#4b474c" :box (:line-width -1)))))
 '(mode-line ((t (:background "dark slate gray" :foreground "#fafafa" :weight normal))))
 '(mode-line-inactive ((t (:background "dim gray" :foreground "#d4d4d4" :weight normal))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:bold nil :foreground "#ffffff" :background nil))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#569cd6" :box nil :weight normal))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#d4d4d4"))))
 '(company-preview-common ((t (:foreground unspecified :background "#252526"))))
 '(company-scrollbar-bg ((t (:background "#252526"))))
 '(company-scrollbar-fg ((t (:background "#333333"))))
 '(company-tooltip ((t (:inherit default :background "#252526"))))
 '(company-tooltip-common ((t (:foreground "#569cd6" :bold t))))
 '(company-tooltip-selection ((t (:background "#264f78"))))
 '(company-tooltip-annotation ((t (:foreground "#888888"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:bold nil :foreground "#4ec9b0" :height 1.1))))
 '(org-level-2 ((((class color) (min-colors 89)) (:bold nil :foreground "#9cdcfe"))))
 '(org-level-3 ((((class color) (min-colors 89)) (:bold nil :foreground "#569cd6"))))
 '(org-level-4 ((((class color) (min-colors 89)) (:bold nil :foreground "#4ec9b0"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#e8e8e8"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#fafafa"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#9cdcfe"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#fafafa"))))
 '(org-link ((((class color) (min-colors 89)) (:underline t :foreground "#4ec9b0"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#6a9955"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#e8e8e8" :background "#111111" :extend t))))
 '(org-quote ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-verse ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-todo ((((class color) (min-colors 89)) (:box (:line-width 1 :color (\, ms-lightred)) :foreground "#f19999" :bold nil))))
 '(org-done ((((class color) (min-colors 89)) (:box (:line-width 1 :color "#b5cea8") :foreground "#b5cea8" :bold nil))))
 '(org-warning ((((class color) (min-colors 89)) (:underline t :foreground "#f16969"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:weight normal :foreground "#f4f4f4" :box (:color "#fafafa") :background "#333333"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#9cdcfe" :height 1.1))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:weight normal :foreground "#fafafa"))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:weight normal :foreground "#569cd6" :height 1.2))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#4b474c"))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#4ec9b0"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#dcdcaa" :weight normal :height 1.2))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#c586c0"))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#fafafa"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#4ec9b0" :bold t :height 1.2))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#dcdcaa"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#6a9955"))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#fafafa"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#e8e8e8" :background "#333333"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#f16969")))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#613214"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) :foreground "#c586c0")))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) :foreground "#e8e8e8")))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) :foreground "#9cdcfe")))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) :foreground "#4ec9b0")))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) :foreground "gold")))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) :foreground "orchid")))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) :foreground "LightSkyBlue")))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) :foreground "gold")))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) :foreground "orchid")))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) :foreground "LightSkyBlue")))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) :foreground "gold")))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) :foreground "orchid")))
 '(rainbow-delimiters-depth-9-face ((((class color) (min-colors 89)) :foreground "LightSkyBlue")))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) :foreground "#f16969")))
 '(diff-header ((t (:foreground "#4ec9b0" :background nil))))
 '(diff-file-header ((t (:foreground "#f4f4f4" :background nil))))
 '(diff-hunk-header ((t (:foreground "#fafafa" :background "#333333"))))
 '(diff-added ((t (:foreground "#e8e8e8" :background "#39422a"))))
 '(diff-removed ((t (:foreground "#e8e8e8" :background "#551b1e"))))
 '(diff-changed ((t (:foreground "#e8e8e8" :background "#040e3f"))))
 '(diff-refine-added ((t (:foreground "#f4f4f4" :background "#4b5332"))))
 '(diff-refine-removed ((t (:foreground "#f4f4f4" :background "#74140f"))))
 '(diff-refine-changed ((t (:foreground "#f4f4f4" :background "#141e4f"))))
 '(ivy-confirm-face ((t (:inherit minibuffer-prompt :foreground "#569cd6"))))
 '(ivy-current-match ((t (:background "#264f78" :extend t))))
 '(ivy-highlight-face ((t (:inherit font-lock-builtin-face))))
 '(ivy-match-required-face ((t (:inherit minibuffer-prompt :foreground "#f16969"))))
 '(ivy-minibuffer-match-face-1 ((t (:inherit isearch))))
 '(ivy-minibuffer-match-face-2 ((t (:inherit ivy-minibuffer-match-face-1))))
 '(ivy-minibuffer-match-face-3 ((t (:inherit ivy-minibuffer-match-face-2))))
 '(ivy-minibuffer-match-face-4 ((t (:inherit ivy-minibuffer-match-face-2))))
 '(ivy-minibuffer-match-highlight ((t (:inherit ivy-current-match))))
 '(ivy-modified-buffer ((t (:inherit default :foreground "#9cdcfe"))))
 '(ivy-virtual ((t (:inherit default :foreground "#888888"))))
 '(counsel-key-binding ((t (:foreground "#9cdcfe"))))
 '(swiper-match-face-1 ((t (:inherit ivy-minibuffer-match-face-1))))
 '(swiper-match-face-2 ((t (:inherit ivy-minibuffer-match-face-2))))
 '(swiper-match-face-3 ((t (:inherit ivy-minibuffer-match-face-3))))
 '(swiper-match-face-4 ((t (:inherit ivy-minibuffer-match-face-4))))
 '(swiper-line-face ((t (:foreground "#aeafad" :background "#4b474c" :extend t))))
 '(window-divider ((t (:foreground "gray40"))))
 '(window-divider-last-pixel ((t (:foreground "gray20"))))
 '(window-divider-first-pixel ((t (:foreground "gray60"))))
 '(tab-bar-tab-inactive ((t (:background "#2D2D2D" :foreground "#aeafad"))))
 '(tab-bar-tab ((t (:background "#1e1e1e" :foreground "#ffffff"))))
 '(tab-line ((t (:background "#252526"))))
 '(tab-bar ((t (:background "#1e1e1e"))))
 '(default ((((class color) (min-colors 89)) (:background "#1e1e1e" :foreground "#d4d4d4")))))

(provide-theme 'vscode-dark)
