;;; init-hydra.el --- hydra configuration

;;; Commentary:
;;
;; hydra configuration
;;

;;; Require
(require 'init-packages)

;;; Code:

(require-packages '(hydra
                    ace-window))

(defhydra hydra-org-mode (:foreign-keys warn :exit t)
  ("s" org-insert-structure-template "org template" :column "Edit")
  ("h" org-html-export-to-html "export to html")
  ("t" org-table-create "create table")
  ("i" org-indent-mode "indent mode")
  ("RET" org-meta-return "meta return")
  ("'" org-insert-subheading "insert subheading")
  ("<" org-metaleft "meta left" :column "Meta" :exit nil)
  (">" org-metaright "meta right" :exit nil)
  ("l" org-metaleft "meta left" :exit nil)
  ("r" org-metaright "meta right" :exit nil)
  ("u" org-metaup "meta up" :exit nil)
  ("d" org-metadown "meta down" :exit nil)
  ("L" org-shiftmetaleft "shift meta left" :exit nil)
  ("R" org-shiftmetaright "shift meta right" :exit nil)
  ("U" org-shiftmetaup "shift meta up" :exit nil)
  ("D" org-shiftmetadown "shift meta down" :exit nil)
  ("SPC" nil "quit")
  ("C-q" nil "quit"))

(defhydra hydra-lsp-mode (:foreign-keys warn :exit t)
  ("d" lsp-find-definition "find defined" :column "LSP")
  ("r" lsp-find-references "find references")
  ("i" lsp-find-implementation "find implementation")
  ("t" lsp-find-type-definition "find type definition")
  ("o" lsp-describe-thing-at-point "documentation")
  ("R" lsp-workspace-restart "lsp restart")
  ("b" lsp-rename "lsp rename")
  ("f" lsp-format-buffer "lsp format")
  ("SPC" nil "quit")
  ("C-q" nil "quit"))

(defun cond-keymode-with-modes ()
  "Select the keymap of hydara according to current mode."
  (interactive)
  (when (eq major-mode 'org-mode)
    (hydra-org-mode/body))
  (when lsp-mode
    (hydra-lsp-mode/body)))

(global-set-key
 (kbd "C-r")
 (defhydra hydra-edit (:foreign-keys warn :exit t)
   ("u" undo "undo" :column "Edit" :exit nil)
   ("U" undo-redo "redo" :exit nil)
   ("h" anzu-query-replace "replace")
   ("H" anzu-query-replace-regexp "replace regexp")
   (";" comment-line "comment line")
   ("C-;" comment-region "comment region")
   ("m" format-all-buffer "format buffer")
   ("~" revert-buffer "revert buffer")
   (":" iedit-mode "iedit")
   ("`" normal-mode "vim normal")
   ("\"" grammatical-edit-wrap-double-quote "warp \"\"")
   ("'" grammatical-edit-wrap-single-quote "warp ''")
   ("[" grammatical-edit-wrap-bracket "warp []")
   ("{" grammatical-edit-wrap-curly "warp {}")
   ("(" grammatical-edit-wrap-round "warp ()")
   (")" grammatical-edit-unwrap "unwarp")
   ("RET" grammatical-edit-jump-out-pair-and-newline "jump and newline")

   ("gg" goto-line "goto line" :column "Navigate")
   ("gw" avy-goto-word-1 "goto word")
   ("gc" avy-goto-char-2 "goto char2")
   ("v" View-scroll-half-page-forward "page down" :exit nil)
   ("V" View-scroll-half-page-backward "page up" :exit nil)
   ("," goto-last-change "goto last change")
   ("DEL" hungry-delete-backward "hungry delete")
   ("s" ctrlf-forward-default "search forward")
   ("S" ctrlf-forward-alternate "regexp forward")
   ("r" ctrlf-backward-default "search backward")
   ("R" ctrlf-backward-alternate "regexp backward")
   ("b" symbol-overlay-rename "symbol rename")
   ("_" ctrlf-forward-symbol "search symbol")
   ("." ctrlf-forward-symbol-at-point "search symbol as point")
   ("=" er/expand-region "expand region")

   ("C-r" nil "exit")
   ("SPC" nil "exit")))

(defhydra hydra-low-frequency (:foreign-keys warn :exit t)
  ("ah" awesome-tab-move-current-tab-to-left "move tab to left" :column "View" :exit nil)
  ("al" awesome-tab-move-current-tab-to-right "move tab to right" :exit nil)
  ("a0" awesome-tab-select-beg-tab "select first tab")
  ("a$" awesome-tab-select-end-tab "select last tab")
  ("aa" awesome-tab-switch-group "switch tab group")
  ("u" uuidgen "uuidgen" :column "Fun")
  ("v" vundo "vundo")
  ("f" defined/get-buffer-file-path "get file path")
  ("c" projectile-run-async-shell-command-in-root "async run command")
  ("r" projectile-toggle-project-read-only "project readonly")
  ("m" xterm-mouse-mode "xterm mouse")
  ("p" poetry "poetry" :column "Langs")
  ("P" pyvenv-workon "pyvenv workon")
  ("oo" conda-env-activate "conda activate")
  ("od" conda-env-deactivate "conda deactivate")
  ("SPC" nil "exit"))

(global-set-key
 (kbd "C-q")
 (defhydra hydra-high-frequency (:foreign-keys warn :exit t)
   ("c" consult-recent-file "recent file" :column "Navigate")
   ("C" consult-bookmark "bookmark")
   ("b" consult-project-buffer "project buffer")
   ("p" projectile-switch-project "switch project")
   ("f" projectile-find-file "project file")
   ("q" treemacs "treemacs")
   ("d" xref-find-definitions "find definitions")
   ("r" xref-find-references "find references")
   ("w" xref-find-definitions-other-window "references other window")
   ("i" consult-imenu "semantic imenu")
   ("jj" citre-jump "citre jump")
   ("jb" citre-jump-back "citre jump back")
   ("jp" citre-peek "citre peek")
   ("ju" citre-update-this-tags-file "citre update tags")
   ("t" vterm "vterm" :column "Tools")
   ("T" projectile-run-vterm "projectile vterm")
   ("v" evil-mode "evil")
   ("kt" kill-this-buffer "kill this buffer")
   ("kb" kill-buffer "kill other buffer")
   ("kr" eval-buffer "eval buffer")
   ("C-w" hydra-low-frequency/body "frequency")
   ("C-q" cond-keymode-with-modes "conds")
   ("," awesome-tab-backward-tab "backward tab" :column "Tabs" :exit nil)
   ("." awesome-tab-forward-tab "forward tab" :exit nil)
   ("1" awesome-tab-select-visible-tab "tab 1")
   ("2" awesome-tab-select-visible-tab "tab 2")
   ("3" awesome-tab-select-visible-tab "tab 3")
   ("4" awesome-tab-select-visible-tab "tab 4")
   ("5" awesome-tab-select-visible-tab "tab 5")
   ("6" awesome-tab-select-visible-tab "tab 6")
   ("7" awesome-tab-select-visible-tab "tab 7")
   ("8" awesome-tab-select-visible-tab "tab 8")
   ("9" awesome-tab-select-visible-tab "tab 9")
   ("SPC" nil "exit")))

(provide 'init-hydra)

;;; init-hydra.el ends here
